services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: petunia
      POSTGRES_PASSWORD: petunia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file: ".env"
    

volumes:
  postgres_data: